feat(rebrand)!: change archifiltre to archifiltre-docs
SocialGouv/archifiltre-site pull request #256
Opened 2022-01-28 13:09 UTC by lsagetlethias

- "Suite Archifiltre" ou "outils Archifiltre" ou "produits Archifiltre" évoqués dans les pages de contribution
- "Archifiltre" => "Docs par Archifiltre" évoqué quand on parle du produit lui même
- "Docs" évoqué dans les faq par exemple quand "Docs par Archifriltre" est déjà mentionné une fois
- LICENCE dans le packagejson mise à jour
- mise à jour membres équipe
- changement des remote git
- remplacement du lien "latest-build" pour la page des "next-release"

2022-01-28 23:57 UTC, gary-van-woerkens approved these changes

2022-01-31 08:46 UTC, Alezco commented on .github/workflows/update-license.yml
> +name: Update LICENSE date
Un petit peu overkill mais cool ! :D

2022-01-31 08:51 UTC, Alezco requested changes

2022-01-31 08:51 UTC, Alezco commented on src/pages/co-construction.tsx
> +        La suite Archifiltre sont des produits développés en amélioration
```suggestion
        Les logiciels de la suite Archifiltre sont des produits développés en amélioration
```

2022-01-31 08:51 UTC, Alezco commented on src/pages/co-construction.tsx
> +            utilisateur·trice·s, à propos des outil Archifiltre. Durant cet
```suggestion
            utilisateur·trice·s, à propos des outils Archifiltre. Durant cet
```

2022-01-31 08:51 UTC, Alezco commented on static/latest-build.html
> +    <p>Redirection vers les version en cours de développement ...</p>
```suggestion
    <p>Redirection vers les versions en cours de développement ...</p>
```

2022-01-31 10:21 UTC, lsagetlethias commented on .github/workflows/update-license.yml
> +name: Update LICENSE date
Yes 😅  C'est un copié collé des autres répos donc pas de temps cramé là dessus

2022-01-31 10:52 UTC, Alezco approved these changes

2022-01-31 15:22 UTC, mehdilouraoui approved these changes

2022-02-02 18:10 UTC, merged